## ESTADO
INSERT INTO ESTADO (IDESTADO, DES_ESTADO) VALUES (0, 'Activo');
INSERT INTO ESTADO (IDESTADO, DES_ESTADO) VALUES (1, 'Inactivo');

## USUARIO ADMINISTRADOR
INSERT INTO PERSONA (IDPERSONA,NOMBRE1,NOMBRE2,APELLIDO1,APELLIDO2,NIT,DPI,GENERO,CARNET) 
            VALUES (0, 'ADMIN', 'ADMIN', 'ADMIN', 'ADMIN', '123456789','1234567891234', 'M', '319019973');

INSERT INTO EMPLEADO (IDEMPLEADO, FECHA_INGRESO_EMPLEADO, SALARIO, PUESTO, PERSONA_IDPERSONA, ESTADO_IDESTADO) 
            VALUES (0, TO_DATE('08-10-2022', 'DD-MM-YYYY'), '0.00', 'SYSADMIN', 0, 0);

